In [34]:
import pandas  as  pd
from utils import obtenir_donnees_meteo
import sqlite3

In [31]:
df_ville =  pd . read_csv("data/villes.csv")
df_ville

                ville
0               Lille
1             Roubaix
2           Tourcoing
3           Dunkerque
4              Calais
5   Villeneuve-d'Ascq
6    Boulogne-sur-Mer
7               Douai
8        Valenciennes
9           Wattrelos
10              Arras
11            Cambrai
12           Maubeuge
13   Marcq-en-Baroeul
14               Lens
15         Saint-Omer
16            Béthune
17         Hazebrouck
18        Armentières
19       La Madeleine

In [32]:
donnees_meteo = pd.DataFrame(columns=["ville", "temperature_actuelle", "temperature_ressentie", "temp_minimum", "temp_maximum", "pression atmospherique", "humidite", "vitesse_vent", "direction_vent", "lever_soleil", "coucher_soleil"])

for ville in df_ville["ville"]:
    meteo_ville = obtenir_donnees_meteo(ville)
    if meteo_ville is not None:
        donnees_ville = pd.DataFrame({
            "ville": [ville],
            "temperature_actuelle": [meteo_ville["temperature_actuelle"]],
            "temperature_ressentie": [meteo_ville["temperature_ressentie"]],
            "temp_minimum": [meteo_ville["temp_minimum"]],
            "temp_maximum": [meteo_ville["temp_maximum"]],
            "pression atmospherique": [meteo_ville["pression atmospherique"]],
            "humidite": [meteo_ville["humidite"]],
            "vitesse_vent": [meteo_ville["vitesse_vent"]],
            "direction_vent": [meteo_ville["direction_vent"]],
            "lever_soleil": [meteo_ville["lever_soleil"]],
            "coucher_soleil": [meteo_ville["coucher_soleil"]]
        })
        donnees_meteo = pd.concat([donnees_meteo, donnees_ville], ignore_index=True)

# Sauvegarder le DataFrame dans un fichier CSV
donnees_meteo.to_csv("data/meteo_villes.csv", index=False)

In [39]:
import sqlite3
import pandas as pd

# Charger les données du fichier CSV dans un DataFrame
donnees_meteo = pd.read_csv("data/meteo_villes.csv")

# Créer une base de données
conn = sqlite3.connect("data/meteo_villes.db")

# Créer une table
donnees_meteo.to_sql("meteo", conn, if_exists="replace", index=False)

# Sauvegarder les données et fermer la connexion
conn.commit()
conn.close()